#!/bin/bash

NESTED_STATUS=$(tmux show-option -qv key-table)

if [[ $NESTED_STATUS != "off" ]]; then
  LEFT_STATUS_LINE='#[fg=white,bg=colour240]#{?client_prefix,✠I am enough✠, I am enough }'
  LEFT_STATUS_LINE+='#[default] #{session_name}'
  RIGHT_STATUS_LINE='#{=10:host_short} '
  RIGHT_STATUS_LINE+='#(~/.bin/tmux_battery_charge_indicator)'
  RIGHT_STATUS_LINE+='#[bg=white,fg=colour240] %H:%M '
  RIGHT_STATUS_LINE+='#[bg=colour240,fg=white] %Y-%m-%d '
else
  LEFT_STATUS_LINE='#[fg=red,bg=colour240]#{?client_prefix,✠NESTED✠, NESTED }'
  RIGHT_STATUS_LINE="#[fg=white,bg=colour240] #{host_short} "
fi

tmux set "$@" status-left "$LEFT_STATUS_LINE"
tmux set "$@" status-right "$RIGHT_STATUS_LINE"
